packages:
  - packages/cli
  - packages/e2e
  - packages/extension
  - packages/mcp
  - packages/server
  - packages/vite-plugin-extension-reload
  - packages/website
allowBuilds:
  esbuild: set this to true or false
